# Site settings
url: http://www.iamchristinabot.com
name: 'iamchristinabot.com - Blog'
description: Christina Dobi Blog
github_repo: iamchristinabot/iamchristinabot.github.io


# Gems
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Build Settings
paginate: 10
paginate_path: /blog/page/:num
sass:
  sass_dir: _sass
  style: compressed
