# Site settings
url: https://www.iamchristinabot.com
name: 'iamchristinabot.com - Blog'
description: Christina Dobi Blog
github_repo: iamchristinabot/iamchristinabot.github.io

# Gems
gems:
  - jekyll-sitemap
  - jekyll-feed

plugins:
  - jekyll-paginate

# Build Settings
sass:
  sass_dir: _sass
  style: compressed

# Site Features
featured-tags: true
featured-condition-size: 1
paginate: 10
paginate_path: /blog/page/:num

# Configuration
ga_track_id: UA-12642425-1
twitter_id: iamchristinabot
instagram_id: iamchristinabot
pinterest_id: iamchristinabot
linkedin_id: christinadobi
email: iamchristinabot@gmail.com
